### ISSUE TITLE
what if request.abort

### ISSUE THREAD

**Issue by jhcao23** [yalishizhude/RxWX#3]
Hi @yalishizhude,
What if we want to call the `Observable.cancel` just like calling `wx.request.abort`?
I am curious about how we can match and connect these 2 things?

Thanks!

**Comment by yalishizhude** [comment]
you can use `unsubscribe`
eg.

```
let req = rxwx.request({
  url: 'a website',
})
.subscribe(e => {
  // your code XX
})

setTimeout(() => {
  req.unsubscribe()
  //your code XX will not be excuted
}, 100)
```
